name: Github Actions Test

on:
  push:
    branches: [ "develop", "main" ]

permissions:
  contents: read

env:
  APP_ENV: ${{ (github.ref_name == 'main' && 'prod') || 'develop' }}

jobs:
  deploy:
    name: Deploy DEV
    runs-on: ubuntu-latest
    environment: 
      name: prod
    #environment: 
    #  name: ${{ (github.ref_name == 'main' && 'prod') || 'develop' }}
    # environment: ${{ env.APP_ENV }}

    steps:
    - name: output test
      run: |
        echo "env.APP_ENV:" ${{ env.APP_ENV }}
        echo "job.environment.name:" ${{ job.environment.name }} 
        
